=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.		
=end

limit = 4000000
sum = 0
current_term = 2
previous_term = 1

while current_term < limit
	if current_term % 2 == 0
		sum += current_term
	end
	next_term = current_term + previous_term
	previous_term = current_term
	current_term = next_term
end

puts sum